### ISSUE TITLE
Hunspell extension files hard-coded to public

### ISSUE THREAD

**Issue by robe2** [postgrespro/hunspell_dicts#1]
The hunspell extensions are marked as relocateable, but the extension hard-codes all the dictionaries and configurations installed in public, so trying to install in a different location doesn't work.

Shouldn't public be removed from extension scripts so people can install them where they want?

**Comment by za-arthur** [comment]
Hello.
Thank you for the report!. Fixed.
By the way, now configurations have same name as dictionaries.

**Comment by robe2** [comment]
Thanks.
